# Generated by Django 5.0 on 2024-01-15 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(blank=True, max_length=250, null=True)),
                ('last_name', models.TextField(blank=True, max_length=250, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
