# Generated by Django 5.0 on 2024-01-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_class_student_class_n'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='avata',
            field=models.ImageField(blank=True, null=True, upload_to='avatar/'),
        ),
    ]
