# Generated by Django 5.0 on 2024-02-01 02:48

import student.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_student_avata'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='avata',
            field=models.ImageField(blank=True, null=True, upload_to=student.models.avatar_file_name),
        ),
    ]
