# Generated by Django 5.0.1 on 2024-02-20 02:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0007_student_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="email",
            field=models.TextField(blank=True, null=True),
        ),
    ]
