# Generated by Django 5.0.1 on 2024-02-20 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0009_alter_student_class_n"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="class_n",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student",
                to="student.class",
            ),
        ),
    ]
