# Generated by Django 5.0.1 on 2024-02-27 01:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0010_alter_student_class_n"),
    ]

    operations = [
        migrations.AddField(
            model_name="class",
            name="slug",
            field=models.SlugField(blank=True, default="", max_length=250),
        ),
    ]
